name: silk_ui
description: Minimal, image-first Flutter UI components for FITR-MAE products.
version: 0.0.1
homepage: https://github.com/FITR-MAE/silk_ui
repository: https://github.com/FITR-MAE/silk_ui

environment:
  sdk: ^3.11.4
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.12.0+2
  camera_android: ^0.10.11
  photo_manager: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
